# Generated by Django 4.0.6 on 2022-08-11 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_orderposition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
